model:
  backbone: "nnunet" 
  checkpoint: False #"/home/divyanshu/EFS/segmentation_pretraining/checkpoints/outch3_round2cbtn_round1tcia_best_metric_model.pth"
  max_epochs: 200
  freeze: False
  classifier : "two_way"
  public_weights: "/media/sdb/divyanshu/divyanshu/EFS_V2/medicalnetweights/resnet_18.pth" 
  #"/media/sdb/divyanshu/divyanshu/EFS_V2/medicalnetweights/resnet_18.pth"
  #"/media/sdb/divyanshu/divyanshu/EFS_V3/endpoint_training/best_models/casedetect_resnet18_15to1_batch64_best-model-187-0.67"

data:
  dataset: "image_only"
  size: [128,128,128]
  batch_size: 32  #c
  num_workers: 8 #c
  csv_file: "/media/sdb/divyanshu/divyanshu/project_XX/pilot/csvs/oasis3_csvs/tlv2_train.csv"
  val_csv: "/media/sdb/divyanshu/divyanshu/project_XX/pilot/csvs/oasis3_csvs/tlv2_val.csv"
  test_csv: "/media/sdb/divyanshu/divyanshu/project_XX/pilot/csvs/adni_csvs/tl_test_subsampled_50.csv"
  saliency_map: "/media/sdb/divyanshu/divyanshu/project_XX/pilot/csvs/oasis3_csvs/saliencymap.csv"
  root_dir: "/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets"  #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets/brainage/LONG579" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets/brainage/LONG579" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets/brainage/LONG579" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets/brainage/LONG579" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/datasets" # # #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/non_tumor_brain/abcd/abcd_itmt_preprocessed" #"/media/sdb/divyanshu/divyanshu/longitudinal_fm/healthy_brain/preprocessed_oasis2"
  perturbation_csv: "/media/sdb/divyanshu/divyanshu/longitudinal_fm/pipeline/atlas/csvs/V2_cropped_test.csv"
  collate: 3

optim:
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.00001
  clr: "no"
# v2 model is where the output of the resetnet is directly fed into lstm without batchnorm and relu and output of lstm is put to relu then to classifier 
logger:
  save_dir: "/media/sdb/divyanshu/divyanshu/project_XX/pilot/abcd_or_oasis3_tl_checkpoints"
  save_name: "tlv1_oasis_resnet50_hiddim512_binarycrossentropy_batch32lr0001_cosineaneal_dropout0.2_best-model-{epoch:02d}-{f1:.2f}-{auc:.2f}" 
  run_name: "tlv1_oasis_resnet50_hiddim512_binarycrossentropy_batch32lr0001_cosineaneal_dropout0.2"
  project_name: "project_xx"
gpu:
  visible_device: "0" 
infer:
  checkpoints: "/media/sdb/divyanshu/divyanshu/project_XX/pilot/oasis3_abcd_joint_checkpoints/tlv1_abcdoasis_resnet50_hiddim512_binarycrossentropy_batch32lr0001_cosineaneal_dropout0.2_best-model-30-0.85-0.94"
  header_name: "ABIDE_20_1fmft"
train: 
  freeze: "no"
  finetune: "no"
  weights: "/media/sdb/divyanshu/divyanshu/longitudinal_fm/temporal_learning_latest/simclr_singlescan_checkpoints/bchpostop_easiertransform_latent2048_adamwnewschrluer_simclr_singlescan_FM_train_RESNET50_1000epcs_batch32_lr0.0001_best-model-epoch=136-train_loss=0.00.ckpt"
  
  #"/media/sdb/divyanshu/divyanshu/foundation_model/code/simclr/checkpoints/WORKS_V3_jointcsvalldataV3_easiertransform_latent2048_adamwnewschrluer_simclr_singlescan_FM_train_RESNET50_1000epcs_batch32_lr0.0001_best-model-epoch=07-train_loss=0.00.ckpt" 
  
  # /media/sdb/divyanshu/divyanshu/foundation_model/code/simclr/checkpoints/WORKS_V1_abcd_adni_bchpreop_cbtnpreop_FM_train_RESNET50_1000epcs_batch64_lr0.0001_best-model-epoch=57-train_loss=0.00.ckpt
  #"/media/sdb/divyanshu/divyanshu/foundation_model/code/simclr/checkpoints/WORKS_V3_jointcsvalldataV3_easiertransform_latent2048_adamwnewschrluer_simclr_singlescan_FM_train_RESNET50_1000epcs_batch32_lr0.0001_best-model-epoch=07-train_loss=0.00.ckpt" 
  #"/media/sdb/divyanshu/divyanshu/foundation_model/code/simclr/checkpoints/jointcsvalldataV2_1channelsameimage_singlescan_FM_train_RESNET50_1000epcs_batch32_lr0.0001_best-model-epoch=19-train_loss=0.00.ckpt"" #"/media/sdb/divyanshu/divyanshu/foundation_model/code/simclr/checkpoints/jointcsvalldataV2_hardercrop_simclr_singlescan_FM_train_RESNET50_1000epcs_batch32_lr0.0001_best-model-epoch=30-train_loss=0.00.ckpt" 
  #"/media/sdb/divyanshu/divyanshu/foundation_model/code/simclr/checkpoints/jointcsvalldataV2_1channelsameimage_singlescan_FM_train_RESNET50_1000epcs_batch32_lr0.0001_best-model-epoch=19-train_loss=0.00.ckpt"

  