data:
  batch_size: 16
  collate: 2
  num_workers: 4
  root_dir: ./data/sample/processed
  test_csv: ./data/csvs/input_scans.csv
  train_csv: ./data/csvs/train_set_100.csv
  val_csv: ./data/csvs/val_set_100.csv
gpu:
  device: cpu
  visible_device: '0'
infer:
  checkpoints: ./checkpoints/idh_model.76
logger:
  project_name: brainage
  run_name: ExperimentName_trainconfigs
  save_dir: ./Checkpoints
  save_name: ExperimentName_trainconfigs_checkpoint-{epoch:02d}-{loss:.2f}-{metric:.2f}
optim:
  clr: 'no'
  lr: 0.0001
  max_epochs: 200
  momentum: 0.9
  weight_decay: 1.0e-05
train:
  finetune: 'yes'
  freeze: 'no'
  weights: path/to/brainiac/weights
