data:
  batch_size: 16  
  num_workers: 4 
  train_csv: "./data/csvs/train_set_100.csv"
  val_csv: "./data/csvs/val_set_100.csv"
  test_csv: "./data/csvs/sample.csv"
  root_dir: "./data/preprocessed_data"
  collate: 1

optim:
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.00001
  clr: "no"
  max_epochs: 200

logger:
  save_dir: "./Checkpoints"
  save_name: "ExperimentName_trainconfigs_checkpoint-{epoch:02d}-{loss:.2f}-{metric:.2f}"
  run_name: "ExperimentName_trainconfigs"
  project_name: "brainage"

gpu:
  visible_device: "1" 

infer:
  checkpoints: "path/to/checkpoints"

train: 
  freeze: "no"
  finetune: "yes"
  weights: "path/to/brainiac/weights"
  
